### ISSUE TITLE
Hops Additions Text

### ISSUE THREAD

**Issue by mariopareto** [avollkopf/cbpi4-PIDBoil#3]
Hi Alexander!

First of all Id like to thank you for putting together the plugins and updates for CBPI 4!! Im setting CBPI4 for the first time and noticed that on the new PIDBoil we can't set anymore the text that comes up with each hop addition, it gets standard "hops_1"..."hops_6" text. It it possible to upgrade it so we can type like "50g Citra"?

best regards

**Comment by avollkopf** [comment]
I need to think about on how this can be implemented. A text is easy, but netx thing would be also to pull that information from beerxml, BF API,.... and insert it into the boil step. 

This is anyhow the wrong place for the request as this is only the kettly logic. It needs to be implemtned in craftbeerpi4. You should open an issue in the cxorresponding repo, but it should be the repo in the craftbeerpi organization as i am working together with Manuel on that repo.

Anyhow, we are currently in the process to prepare a realase with the existing features of the development branch. Afterwards there is already a list of other topics that need to be finished and then we can look into this one.
