### ISSUE TITLE
Enhancement: Sample Time Input

### ISSUE THREAD

**Issue by Btazbt** [avollkopf/cbpi4-PIDBoil#9]
Can you change the Sample Time to be an input rather than a dropdown of only 2 and 5.  My system doesn't need the precision and 15 or maybe even 30s would be enough.  I tend to see my heat stick cycling on and off which keeps me within my target temp extremely accurate, but I don't need that precision.

**Comment by avollkopf** [comment]
Not sure if I understand you correctly, but this sampling time has nothing to do with the on/off cycles of your heating element. I assume you are talking about the interval / sampling time of the actor itself. Try using the GPIOPWMactor with a frequency of 0.033.  This value here should not be changed as it might completely mess up the PID calculation.

**Comment by avollkopf** [comment]
If still an issue, please follow up. Otherwise it'll be closed.
